name: Hello World
on: workflow_dispatch
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Build step
              run: echo "This is build step"
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Testing step
              run: echo "This is test step"
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Deploy step
              run: echo "This is deploy step"