# push and pull triggers from any branch
name: Hello World
on: push
jobs:
    build:
        runs-on: latest
        steps:
            - name: Build step
              run: echo "This is build step"
