# push and pull triggers from any branch
name: Hello World
# workflow for only specific branches, when code changes are pushed to specific branches then only the workflow triggers
on:
    push:
        branches:
            - main
            - develop
            - 'release/**'
    pull_request:
        types:
            - opened

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Build step
              run: echo "Hello, ${{ secrets.DOCKER_PASSWORD }}"




